// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations must go through the session/direct connection (5432);
    // the runtime DATABASE_URL points at the transaction pooler (6543).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
